Repository Paivola-Student-Innovation-Lab/DailyCrypt, pull requests merged in 2024-01, with the labels that each got.

#7 fix memory leak
  client/src/hooks/useChunking.ts
  client/src/utils/Checkfilesize.ts
Labels: bug, functionality

#19 Guide for extracting files
  client/public/images/linux/linux5.png
  client/public/images/linux/linux6.png
  client/public/images/linux/linux7.png
  client/public/images/mac/mac4.png
  client/public/images/mac/mac5.png
  client/public/images/windows/windows4.png
  client/public/images/windows/windows5.png
  client/public/images/windows/windows6.png
  client/public/images/windows/windows7.png
  client/src/components/Tabpanel.tsx
  client/src/languages/en.json
  client/src/languages/fi.json
Labels: enhancement, accessibility

#20 update readme
  README.md
Labels: documentation
